# Generated by Django 5.2 on 2025-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneluser',
            name='role',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('operator', 'Operator'), ('provider', 'Provider'), ('client', 'Client'),
                         ('user', 'User')], default='operator', max_length=100),
        ),
    ]
