# Generated by Django 5.2 on 2025-05-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_paneluser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneluser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('provider', 'Provider'), ('client', 'Client'), ('user', 'User')], default='user', max_length=100),
        ),
    ]
