# Generated by Django 5.2 on 2025-05-10 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10,
                                      validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
