# Generated by Django 5.2 on 2025-05-13 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_product_provider_clientorder_providerorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientorder',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='providerorder',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='clientorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
