# Generated by Django 5.2 on 2025-04-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_productcategory_provider_product_category_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ManyToManyField(blank=True, to='panel.provider'),
        ),
    ]
