# Generated by Django 5.2 on 2025-05-13 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_clientorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clientorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='providerorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
