# Generated by Django 5.2 on 2025-05-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='clientorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='providerorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='providerorder',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CatalogProduct',
        ),
        migrations.DeleteModel(
            name='ClientOrder',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProviderOrder',
        ),
    ]
