# Generated by Django 5.2 on 2025-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_category_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='in_progress'),
        ),
    ]
