# Generated by Django 5.2 on 2025-05-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='in_progress'),
        ),
    ]
